"use client";

import { FormEvent, useState } from "react";

export default function RegisterPage() {
  const [message, setMessage] = useState(""); const [pending, setPending] = useState(false);
  async function register(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setMessage(""); const form = new FormData(event.currentTarget); const response = await fetch("/api/auth/register", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ displayName: form.get("displayName"), email: form.get("email"), password: form.get("password"), phone: form.get("phone"), address: form.get("address"), stateCode: "TR" }) }); const body = await response.json(); setPending(false); setMessage(response.ok ? "Account created. Check your email to confirm your address, then sign in." : body.error || "Registration failed."); }
  return <main className="login-page"><section className="brand-panel"><a className="logo" href="/"><span className="logo-mark">V</span><span>Valuer<span>AI</span></span></a><div className="brand-copy"><p className="eyebrow">TRIPURA LAUNCH</p><h1>Create your secure valuation workspace.</h1><p>ValuerAI currently accepts production valuations only for Tripura, India.</p></div></section><section className="auth-panel"><form className="auth-card" onSubmit={register}><p className="eyebrow">CREATE ACCOUNT</p><h2>Register as a user</h2><div className="form-grid"><label className="label">Name / company name *<input name="displayName" required minLength={2}/></label><label className="label">Phone number<input name="phone" /></label><label className="label">Email address *<input name="email" type="email" required /></label><label className="label">Password *<input name="password" type="password" required minLength={12} /></label></div><label className="label">Address *<textarea name="address" required minLength={5}/></label><label className="label">State<input value="Tripura" disabled /></label><label className="label">Country<input value="India" disabled /></label>{message && <p className="notice">{message}</p>}<button className="button primary wide" disabled={pending}>{pending ? "Creating account…" : "Create user account"}</button><p className="switch">Already registered? <a href="/app">Sign in</a></p></form></section></main>;
}
